[package]
name = "chat-server"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
argon2 = { version = "0.5.3", features = ["std"] }
chrono = { version = "0.4.39", features = ["serde"] }
jwt-simple = "0.12.11"
serde_json = "1.0.139"
axum-extra = { version = "0.10.0", features = ["typed-header"] }
tower = "0.5.2"
tower-http = { version = "0.6.2", features = ["compression-full", "trace"] }
uuid = { version = "1.14.0", features = ["v4", "v7"] }
sha1 = "0.10.6"
hex = "0.4.3"
mime_guess = "2.0.5"

[dev-dependencies]
http-body-util = "0.1.2"
sqlx-db-tester = "0.5.0"
