### signup user

POST http://localhost:6688/api/signup
Content-Type: application/json
Authorization: Bearer fpKL54jvWmEGVoRdCNj

{
  "workspace": "grad",
  "fullname": "Cristiano Ronaldo",
  "email": "Cris@acme.org",
  "password": "123456"
}

### signin user (valid)

POST http://localhost:6688/api/signin
Content-Type: application/json

{
  "email": "tchen@acme.org",
  "password": "123456"
}

### signin user (invalid)

POST http://localhost:6688/api/signin
Content-Type: application/json

{
  "email": "alice@acme.org",
  "password": "123456"
}


### chat

GET http://localhost:6688/api/chat
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NDEwMDYzMzIsImV4cCI6MTc0MTYxMTEzMiwibmJmIjoxNzQxMDA2MzMyLCJpc3MiOiJjaGF0LXNlcnZlciIsImF1ZCI6ImNoYXRfd2ViIiwiaWQiOjEsIndzX2lkIjoxLCJmdWxsbmFtZSI6IkFsaWNlIENoZW4iLCJlbWFpbCI6ImFsaWNlQGFjbWUub3JnIiwiY3JlYXRlZF9hdCI6IjIwMjUtMDMtMDNUMTI6NDk6MjAuOTUwMjMwWiJ9._xX-VCgBXYLHIjLUScEuqucRltNbtzi2YA05ZAoSEkIOAB7s-9z7LZSfO27jx-T62EU7H8IKGR0uEsJJbx96DA

### chat

GET http://localhost:6688/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NDEwMDYzMzIsImV4cCI6MTc0MTYxMTEzMiwibmJmIjoxNzQxMDA2MzMyLCJpc3MiOiJjaGF0LXNlcnZlciIsImF1ZCI6ImNoYXRfd2ViIiwiaWQiOjEsIndzX2lkIjoxLCJmdWxsbmFtZSI6IkFsaWNlIENoZW4iLCJlbWFpbCI6ImFsaWNlQGFjbWUub3JnIiwiY3JlYXRlZF9hdCI6IjIwMjUtMDMtMDNUMTI6NDk6MjAuOTUwMjMwWiJ9._xX-VCgBXYLHIjLUScEuqucRltNbtzi2YA05ZAoSEkIOAB7s-9z7LZSfO27jx-T62EU7H8IKGR0uEsJJbx96DA
